steps:
- name: 'gcr.io/runseb/kubeless'
  args:
  - function
  - deploy
  - foo
  - --runtime=python3.6
  - --handler=foo.handler
  - --from-file=foo.py
  - --dry-run
  - "|"
  - kubectl
  - apply
  - -f
  - "-"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=geek-demo'

- name: 'gcr.io/runseb/kubeless'
  args:
  - trigger
  - http
  - create
  - foo
  - --function-name
  - foo
  - --dry-run
  - "|"
  - kubectl
  - apply
  - -f
  - "-"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=geek-demo'
