steps:
- name: 'gcr.io/runseb/kubeless'
  args:
  - function
  - deploy
  - foo
  - --runtime=python3.6
  - --handler=foo.handler
  - --from-file=foo.py
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=geek-demo'
