steps:
- name: 'gcr.io/runseb/kubeless@sha256:9744c1fa3a171924e78a638c7271cd8f36a6e974176f9f9292b229da13a079c2'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    /builder/kubeless.bash function ls
    kubeless function deploy foo --runtime=python3.6 --handler=foo.handler --from-file=foo.py --dry-run > function.yaml
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=geek-demo'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'function.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=geek-demo'

- name: 'gcr.io/runseb/kubeless@sha256:9744c1fa3a171924e78a638c7271cd8f36a6e974176f9f9292b229da13a079c2'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    /builder/kubeless.bash function ls
    kubeless trigger http create foo --hostname func.kubeless.sh --path pini --function-name foo --dry-run > trigger.yaml
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=geek-demo'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'trigger.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=geek-demo'
