apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: build
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: init
            image: gcr.io/cloud-builders/git 
            args:
            - "clone"
            - "https://github.com/sebgoa/functions.git"
            - "/tmp"
            volumeMounts:
            - name: source
              mountPath: /tmp
          containers:
          - name: kaniko
            image: gcr.io/kaniko-project/executor
            args: ["--dockerfile=/workspace/Dockerfile","--context=/workspace/","--destination=docker.io/runseb/barbaz"]
            volumeMounts:
            - name: source
              mountPath: /workspace
            - name: docker
              mountPath: "/kaniko/secrets"
              readOnly: true
            env:
            - name: DOCKER_CONFIG
              value: "/kaniko/secrets"
          restartPolicy: OnFailure
          volumes:
          - name: source
            emptyDir: {}
          - name: docker
            secret:
              secretName: docker
