apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: kaniko-test
spec:
  serviceAccountName: build
  source:
    git:
      url: https://github.com/sebgoa/functions.git
      revision: master
  steps:
  - name: test
    image: gcr.io/kaniko-project/executor:latest
    args: ['-d', 'docker.io/runseb/bazbaz', '-f', '/workspace/Dockerfile']
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
  - name: fail
    image: busybox
    args: ['foo']
