apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: kaniko-test
spec:
  serviceAccountName: build
  source:
    git:
      url: https://github.com/sebgoa/functions.git
      revision: master
  template:
    name: kaniko
    arguments:
    - name: IMAGE
      value: docker.io/runseb/bazbaz
